-- TABIB.MA V6 — Supabase/PostgreSQL foundation
create extension if not exists pgcrypto;
create extension if not exists btree_gist;

do $$ begin create type public.user_role as enum ('patient','doctor','pharmacy','clinic_admin','platform_admin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.appointment_status as enum ('requested','confirmed','cancelled','completed','no_show'); exception when duplicate_object then null; end $$;
do $$ begin create type public.document_status as enum ('quarantined','available','rejected'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,phone text,role public.user_role not null default 'patient',created_at timestamptz not null default now());
create table if not exists public.doctor_profiles(id uuid primary key references public.profiles(id) on delete cascade,display_name text not null,specialty text not null,city text not null,bio text,verified boolean not null default false,timezone text not null default 'Africa/Casablanca');
create table if not exists public.clinics(id uuid primary key default gen_random_uuid(),name text not null,city text not null,address text,verified boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.pharmacies(id uuid primary key references public.profiles(id) on delete cascade,name text not null,city text not null,address text,verified boolean not null default false);
create table if not exists public.doctor_clinics(doctor_id uuid references public.doctor_profiles(id) on delete cascade,clinic_id uuid references public.clinics(id) on delete cascade,primary key(doctor_id,clinic_id));
create table if not exists public.doctor_availability(id uuid primary key default gen_random_uuid(),doctor_id uuid not null references public.doctor_profiles(id) on delete cascade,day_of_week smallint not null check(day_of_week between 0 and 6),start_time time not null,end_time time not null,slot_minutes integer not null default 30 check(slot_minutes between 5 and 240),buffer_minutes integer not null default 0 check(buffer_minutes between 0 and 120),active boolean not null default true,check(end_time>start_time));
create table if not exists public.doctor_blocks(id uuid primary key default gen_random_uuid(),doctor_id uuid not null references public.doctor_profiles(id) on delete cascade,start_at timestamptz not null,end_at timestamptz not null,reason text,check(end_at>start_at));
create table if not exists public.appointments(id uuid primary key default gen_random_uuid(),patient_id uuid not null references public.profiles(id) on delete restrict,doctor_id uuid not null references public.doctor_profiles(id) on delete restrict,start_at timestamptz not null,end_at timestamptz not null,status public.appointment_status not null default 'requested',reason text,created_at timestamptz not null default now(),check(end_at>start_at));
alter table public.appointments drop constraint if exists no_overlapping_doctor_appointments;
alter table public.appointments add constraint no_overlapping_doctor_appointments exclude using gist(doctor_id with =,tstzrange(start_at,end_at,'[)') with &&) where(status in('requested','confirmed'));
create table if not exists public.professional_applications(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,requested_role public.user_role not null,license_number text,notes text,status text not null default 'pending',created_at timestamptz not null default now());
create table if not exists public.patient_documents(id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.profiles(id) on delete cascade,storage_path text not null unique,original_name text not null,mime_type text not null,size_bytes bigint not null check(size_bytes>0 and size_bytes<=26214400),status public.document_status not null default 'quarantined',created_at timestamptz not null default now());
create table if not exists public.document_shares(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.patient_documents(id) on delete cascade,shared_by uuid not null references public.profiles(id) on delete cascade,shared_with uuid not null references public.profiles(id) on delete cascade,purpose text,created_at timestamptz not null default now(),expires_at timestamptz not null,revoked_at timestamptz,check(expires_at>created_at));
create table if not exists public.document_access_logs(id bigint generated always as identity primary key,document_id uuid not null references public.patient_documents(id) on delete cascade,actor_id uuid references public.profiles(id) on delete set null,access_type text not null,created_at timestamptz not null default now());
create table if not exists public.audit_logs(id bigint generated always as identity primary key,actor_id uuid references auth.users(id) on delete set null,action text not null,entity_type text,entity_id uuid,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

create or replace function public.is_platform_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='platform_admin') $$;
create or replace function public.get_available_slots(p_doctor_id uuid,p_from timestamptz,p_to timestamptz) returns table(start_at timestamptz,end_at timestamptz) language plpgsql stable security definer set search_path=public as $$
declare d date; rule record; s timestamptz; e timestamptz; step interval; candidate timestamptz; candidate_end timestamptz; tz text;
begin select coalesce(timezone,'Africa/Casablanca') into tz from doctor_profiles where id=p_doctor_id and verified=true; if tz is null then return; end if;
for d in select generate_series((p_from at time zone tz)::date,(p_to at time zone tz)::date,'1 day')::date loop
 for rule in select * from doctor_availability where doctor_id=p_doctor_id and active and day_of_week=extract(dow from d)::int loop
  s=((d+rule.start_time) at time zone tz); e=((d+rule.end_time) at time zone tz); step=make_interval(mins=>rule.slot_minutes+rule.buffer_minutes); candidate=s;
  while candidate + make_interval(mins=>rule.slot_minutes) <= e loop
   candidate_end=candidate+make_interval(mins=>rule.slot_minutes);
   if candidate>=p_from and candidate_end<=p_to and not exists(select 1 from doctor_blocks b where b.doctor_id=p_doctor_id and tstzrange(b.start_at,b.end_at,'[)') && tstzrange(candidate,candidate_end,'[)')) and not exists(select 1 from appointments a where a.doctor_id=p_doctor_id and a.status in('requested','confirmed') and tstzrange(a.start_at,a.end_at,'[)') && tstzrange(candidate,candidate_end,'[)')) then start_at=candidate;end_at=candidate_end;return next;end if;
   candidate=candidate+step;
  end loop;
 end loop;
end loop; end $$;

create or replace function public.book_appointment(p_doctor_id uuid,p_start_at timestamptz,p_end_at timestamptz,p_reason text default null) returns public.appointments language plpgsql security definer set search_path=public as $$ declare a public.appointments; uid uuid:=auth.uid(); begin if uid is null then raise exception 'AUTH_REQUIRED'; end if; if not exists(select 1 from doctor_profiles where id=p_doctor_id and verified=true) then raise exception 'DOCTOR_NOT_BOOKABLE'; end if; if not exists(select 1 from public.get_available_slots(p_doctor_id,p_start_at,p_end_at) s where s.start_at=p_start_at and s.end_at=p_end_at) then raise exception 'SLOT_NOT_AVAILABLE'; end if; insert into appointments(patient_id,doctor_id,start_at,end_at,status,reason) values(uid,p_doctor_id,p_start_at,p_end_at,'requested',p_reason) returning * into a; return a; exception when exclusion_violation then raise exception 'SLOT_ALREADY_BOOKED'; end $$;

alter table public.profiles enable row level security; alter table public.doctor_profiles enable row level security; alter table public.clinics enable row level security; alter table public.pharmacies enable row level security; alter table public.doctor_clinics enable row level security; alter table public.doctor_availability enable row level security; alter table public.doctor_blocks enable row level security; alter table public.appointments enable row level security; alter table public.professional_applications enable row level security; alter table public.patient_documents enable row level security; alter table public.document_shares enable row level security; alter table public.document_access_logs enable row level security; alter table public.audit_logs enable row level security;

create policy profiles_self_select on public.profiles for select using(auth.uid()=id or public.is_platform_admin());
create policy profiles_self_update on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id);
create policy doctors_public_select on public.doctor_profiles for select using(verified=true or auth.uid()=id or public.is_platform_admin());
create policy clinics_public_select on public.clinics for select using(verified=true or public.is_platform_admin());
create policy pharmacies_public_select on public.pharmacies for select using(verified=true or auth.uid()=id or public.is_platform_admin());
create policy doctor_availability_read on public.doctor_availability for select using(doctor_id=auth.uid() or exists(select 1 from doctor_profiles d where d.id=doctor_availability.doctor_id and d.verified=true) or public.is_platform_admin());
create policy appointments_patient_select on public.appointments for select using(patient_id=auth.uid() or doctor_id=auth.uid() or public.is_platform_admin());
create policy appointments_patient_update on public.appointments for update using(patient_id=auth.uid()) with check(patient_id=auth.uid());
create policy appointments_doctor_update on public.appointments for update using(doctor_id=auth.uid()) with check(doctor_id=auth.uid());
create policy applications_self on public.professional_applications for insert with check(user_id=auth.uid()); create policy applications_read on public.professional_applications for select using(user_id=auth.uid() or public.is_platform_admin());
create policy docs_owner_select on public.patient_documents for select using(owner_id=auth.uid() or exists(select 1 from document_shares s where s.document_id=patient_documents.id and s.shared_with=auth.uid() and s.revoked_at is null and s.expires_at>now()));
create policy docs_owner_insert on public.patient_documents for insert with check(owner_id=auth.uid()); create policy docs_owner_update on public.patient_documents for update using(owner_id=auth.uid()) with check(owner_id=auth.uid()); create policy docs_owner_delete on public.patient_documents for delete using(owner_id=auth.uid());
create policy shares_owner_or_recipient on public.document_shares for select using(shared_by=auth.uid() or shared_with=auth.uid()); create policy shares_owner_insert on public.document_shares for insert with check(shared_by=auth.uid() and exists(select 1 from patient_documents d where d.id=document_id and d.owner_id=auth.uid())); create policy shares_owner_update on public.document_shares for update using(shared_by=auth.uid()) with check(shared_by=auth.uid());
create policy access_logs_self on public.document_access_logs for insert with check(actor_id=auth.uid()); create policy access_logs_read on public.document_access_logs for select using(actor_id=auth.uid() or public.is_platform_admin());
create policy audit_self on public.audit_logs for insert with check(actor_id=auth.uid()); create policy audit_admin_read on public.audit_logs for select using(public.is_platform_admin());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('patient-documents','patient-documents',false,26214400,array['application/pdf','image/jpeg','image/png','image/webp']) on conflict(id) do update set public=false,file_size_limit=26214400,allowed_mime_types=excluded.allowed_mime_types;
create policy storage_patient_insert on storage.objects for insert to authenticated with check(bucket_id='patient-documents' and (storage.foldername(name))[1]=auth.uid()::text);
create policy storage_patient_select on storage.objects for select to authenticated using(bucket_id='patient-documents' and ((storage.foldername(name))[1]=auth.uid()::text or exists(select 1 from patient_documents d join document_shares s on s.document_id=d.id where d.storage_path=name and s.shared_with=auth.uid() and s.revoked_at is null and s.expires_at>now() and d.status='available')));
create policy storage_patient_delete on storage.objects for delete to authenticated using(bucket_id='patient-documents' and (storage.foldername(name))[1]=auth.uid()::text);
