import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { validateJsonBody, requireSameOrigin } from '@/lib/validation'
import { decideRecord, RawDoctor } from '@/lib/directory/importer'
export async function POST(req:Request){
 const o=requireSameOrigin(req); if(!o.ok)return NextResponse.json({error:o.error},{status:o.status})
 const s=await createClient(); const {data:{user}}=await s.auth.getUser(); if(!user)return NextResponse.json({error:'AUTH_REQUIRED'},{status:401})
 const {data:p}=await s.from('profiles').select('role').eq('id',user.id).single(); if(p?.role!=='platform_admin')return NextResponse.json({error:'FORBIDDEN'},{status:403})
 const body=await validateJsonBody(req, 2_000_000); if(!body.ok)return NextResponse.json({error:body.error},{status:body.status})
 const b=body.data as any; const sourceCode=String(b.sourceCode||''); const mode=b.mode==='commit'?'commit':'dry_run'; const rows=Array.isArray(b.records)?b.records as RawDoctor[]:[]
 const {data:source}=await s.from('directory_sources').select('*').eq('code',sourceCode).single(); if(!source)return NextResponse.json({error:'UNKNOWN_SOURCE'},{status:400})
 const decisions=[] as any[]; const seen=[] as any[]
 for(const row of rows){const d=decideRecord(row,{code:source.code,permittedForImport:source.permitted_for_import,robotsRequired:source.robots_required,termsUrl:source.terms_url,license:source.license_name},seen);decisions.push({key:row.sourceRecordKey,action:d.action,reason:d.reason});if(d.doctor)seen.push(d.doctor)}
 if(mode==='dry_run')return NextResponse.json({mode,source:source.code,summary:{seen:rows.length,accepted:decisions.filter(x=>x.action==='accepted').length,rejected:decisions.filter(x=>x.action==='rejected').length,duplicates:decisions.filter(x=>x.action==='duplicate').length},decisions})
 const {data:run,error:runError}=await s.from('directory_import_runs').insert({source_id:source.id,mode:'commit',status:'running',initiated_by:user.id,records_seen:rows.length}).select('id').single(); if(runError)return NextResponse.json({error:runError.message},{status:400})
 let accepted=0,rejected=0,duplicates=0,newCount=0,updated=0
 for(let i=0;i<rows.length;i++){const row=rows[i];const d=decideRecord(row,{code:source.code,permittedForImport:source.permitted_for_import,robotsRequired:source.robots_required},[]);if(d.action==='rejected'){rejected++;await s.from('directory_import_records').insert({run_id:run.id,source_record_key:row.sourceRecordKey,action:'rejected',reason:d.reason});continue}if(d.action==='duplicate'){duplicates++;await s.from('directory_import_records').insert({run_id:run.id,source_record_key:row.sourceRecordKey,action:'duplicate',reason:d.reason});continue}accepted++;const doc=d.doctor!;const {data:existing}=await s.from('directory_doctors').select('id').eq('normalized_name',doc.normalizedName).eq('city',doc.city||'').eq('normalized_specialty',doc.normalizedSpecialty).maybeSingle();let doctorId=existing?.id;if(doctorId){updated++;await s.from('directory_doctors').update({full_name:doc.fullName,specialty:doc.specialty,region:doc.region,professional_address:doc.address,public_phone:doc.phone,public_email:doc.email,website_url:doc.website,source_verified:true,verification_status:'source_verified',source_last_seen_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',doctorId)}else{const ins=await s.from('directory_doctors').insert({full_name:doc.fullName,normalized_name:doc.normalizedName,specialty:doc.specialty,normalized_specialty:doc.normalizedSpecialty,city:doc.city,region:doc.region,professional_address:doc.address,public_phone:doc.phone,public_email:doc.email,website_url:doc.website,source_verified:true,verification_status:'source_verified',source_last_seen_at:new Date().toISOString()}).select('id').single();if(ins.error)continue;doctorId=ins.data.id;newCount++}await s.from('directory_doctor_sources').upsert({doctor_id:doctorId,source_id:source.id,source_record_key:row.sourceRecordKey,source_profile_url:row.sourceProfileUrl,observed_at:new Date().toISOString()},{onConflict:'source_id,source_record_key'});await s.from('directory_import_records').insert({run_id:run.id,source_record_key:row.sourceRecordKey,action:existing?'updated':'new',doctor_id:doctorId})}
 await s.from('directory_import_runs').update({status:'completed',records_accepted:accepted,records_rejected:rejected,records_new:newCount,records_updated:updated,records_merged:duplicates,finished_at:new Date().toISOString()}).eq('id',run.id)
 await s.from('audit_logs').insert({actor_id:user.id,action:'directory.import.commit',entity_type:'directory_import_run',entity_id:run.id,metadata:{source:source.code,mode}})
 return NextResponse.json({runId:run.id,summary:{seen:rows.length,accepted,rejected,duplicates,new:newCount,updated}})
}
