'use client';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';

export default function ReschedulePage(){
 const {id}=useParams<{id:string}>(); const [date,setDate]=useState(''); const [slots,setSlots]=useState<any[]>([]); const [selected,setSelected]=useState<any>(); const [doctor,setDoctor]=useState<any>(); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/appointments/mine',{cache:'no-store'}).then(r=>r.json()).then(j=>{const a=(j.appointments||[]).find((x:any)=>x.id===id); if(a){setDoctor(a.doctor_profiles); const d=new Date(a.start_at); setDate(new Intl.DateTimeFormat('en-CA',{timeZone:a.doctor_profiles?.timezone||'Africa/Casablanca'}).format(d));}})},[id]);
 useEffect(()=>{if(!date||!doctor?.id)return; const from=new Date(`${date}T00:00:00`).toISOString(); const to=new Date(`${date}T23:59:59`).toISOString(); fetch(`/api/public/doctors/${doctor.id}/slots?date=${date}`,{cache:'no-store'}).then(r=>r.json()).then(j=>{setSlots(j.slots||[]);setSelected(undefined);});},[date,doctor]);
 async function submit(){if(!selected)return;setBusy(true);setMsg('');try{const r=await fetch('/api/appointments/reschedule',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({appointment_id:id,start_at:selected.start_at,end_at:selected.end_at})});const j=await r.json();if(!r.ok){setMsg(j.error||'Créneau indisponible');return;}window.location.href='/account/appointments';}finally{setBusy(false)}}
 return <main className="wrap"><div className="card"><h1>Reprogrammer</h1><p className="muted">{doctor?`Dr ${doctor.display_name} · ${doctor.specialty}`:'Chargement…'}</p><label>Date<br/><input type="date" value={date} min={new Date().toISOString().slice(0,10)} onChange={e=>setDate(e.target.value)}/></label><h2>Créneaux</h2><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}}>{slots.map(s=><button key={s.start_at} onClick={()=>setSelected(s)} aria-pressed={selected?.start_at===s.start_at}>{new Date(s.start_at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit',timeZone:doctor?.timezone||'Africa/Casablanca'})}</button>)}</div><button className="btn" disabled={!selected||busy} onClick={submit} style={{marginTop:18}}>{busy?'Enregistrement…':'Confirmer le nouveau créneau'}</button>{msg&&<p role="alert">{msg}</p>}</div></main>;
}
